title: Open Redistricting
description: empowering everyone to participate
url: https://alecramsay.github.io
baseurl: ''
author:
  name: Alec Ramsay
  email: alec@openredistricting.net

# Build settings
markdown: kramdown
highlighter: rouge
# theme: hyde
remote_theme: hyde

# Hyde theme settings
sidebar-about-description: "Open Redistricting"
sidebar-nav-links:
  Home: "/"
  About: "/about/"
  Blog: "/blog/"