title: Open Redistricting
description: All about open redistricting
url: https://alecramsay.github.io
baseurl: ''

# Build settings
markdown: kramdown
highlighter: rouge
# theme: hyde
remote_theme: hyde

# Hyde theme settings
sidebar-about-description: "Open Redistricting"
sidebar-nav-links:
  Home: "/"
  About: "/about/"
  Archive: "/archive/"